import type { Metadata } from 'next'
import './globals.css'
import { dmMono, dmSans } from '@/fonts'

export const metadata: Metadata = {
  title: 'Manuel De Toma',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className='md:text-lg'>
      <body
        className={`${dmMono.variable} ${dmSans.variable} dark:bg-neutral-800 dark:text-gray-100`}
      >
        {children}
      </body>
    </html>
  )
}
